### ISSUE TITLE
Feature request: allow components to be excluded from log-render 

### ISSUE THREAD

**Issue by k-sheth** [rkit/react-transform-log-render#1]
Thanks for the wonderful lib. Could you add a feature to ignore certain files / components ? I have some lower level components which render often and I want to exclude them from the log while still keeping th log for higher level components - an exclude option (which takes list of files / names) in the config would be ideal.

thanks

**Comment by rkit** [comment]
Good idea, I will try to do.

**Comment by rkit** [comment]
I released a new version (1.0.0) with this ability
https://github.com/rkit/react-transform-log-render#includeexclude-components-by-name

**Comment by k-sheth** [comment]
Thank you!
